menu arreglado
bakerevil/proyecto pull request #4
Opened 2021-12-01 18:14 UTC by Andrik2406

Se borro mi codigo y lo volvi a subir

2021-12-01 23:48 UTC, abraham1669 requested changes

2021-12-01 23:48 UTC, abraham1669 commented on index.html
> +<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="
La etiqueta link debe de estar dentro de la etiqueta head no dentro de la etiquieta body, corregir

2021-12-01 23:48 UTC, abraham1669 commented on index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
Comentario similar al anterior

2021-12-01 23:48 UTC, abraham1669 commented on index.html
> +<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
Comentario similar al anterior

2021-12-01 23:48 UTC, abraham1669 commented on index.html
> +<link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,600;0,800;1,400&display=swap" rel="stylesheet">
Comentario similar al anterior

2021-12-01 23:48 UTC, abraham1669 commented on index.html
> +    <link rel="stylesheet" href="css/style.css">
Comentario similar al anterior

2021-12-01 23:48 UTC, abraham1669 commented on index.html
>  <body>
Revisar las aperturas e inicios de Body y Head, al parecer están duplicados

2021-12-01 23:48 UTC, abraham1669 commented on index.html
> +                    <hr color="yellow">
Eliminar el atributo color ya que está depreciado, cambiarlo por una clase y añadir el estilo de css

2021-12-01 23:48 UTC, abraham1669 commented on index.html
>  </html>
Por convención, se debe dejar al final de cada documento una línea en blanco, añadirla

2021-12-13 23:23 UTC, abraham1669 commented on index.html
>  </html>
Se soluciona en commit e5027a8

2021-12-15 15:32 UTC, Andrik2406 commented on index.html
>  <body>
ya se reviso y se elimino los duplicados

2021-12-15 15:32 UTC, Andrik2406 commented on index.html
> +    <link rel="stylesheet" href="css/style.css">
ya se reviso y se elimino los duplicados

2021-12-15 15:32 UTC, Andrik2406 commented on index.html
> +<link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,600;0,800;1,400&display=swap" rel="stylesheet">
ya se reviso y se elimino los duplicados

2021-12-15 15:32 UTC, Andrik2406 commented on index.html
> +<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
ya se reviso y se elimino los duplicados

2021-12-15 15:32 UTC, merged

2021-12-15 15:32 UTC, Andrik2406 commented on index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
ya se reviso y se elimino los duplicados